"use client";
import { FormEvent, useEffect, useState } from "react";
type Project={title:string;type:string;description:string;stack:string;href:string};
export default function Portfolio({projects,skills}:{projects:Project[];skills:string[]}){
 const [sent,setSent]=useState(false);
 useEffect(()=>{const els=[...document.querySelectorAll<HTMLElement>(".reveal")];const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.12});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSent(true);e.currentTarget.reset()}
 return <main>
 <header className="nav"><a className="logo" href="#top">MR<span>.</span></a><nav><a href="#about">About</a><a href="#work">Work</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a className="navCta" href="#contact">Let's talk ↗</a></header>
 <section id="top" className="hero wrap"><div className="heroCopy reveal"><p className="eyebrow">Developer · Designer · Creative Technologist</p><h1>I build digital experiences with <i>clarity</i> and character.</h1><p className="heroText">Hi, I’m Maya. I turn ambitious ideas into thoughtful websites and products — combining engineering, visual design and a sharp eye for detail.</p><div className="actions"><a className="button primary" href="#work">View selected work</a><a className="button secondary" href="#contact">Start a conversation</a></div><div className="miniStats"><div><strong>06+</strong><span>Years creating</span></div><div><strong>32</strong><span>Projects shipped</span></div><div><strong>∞</strong><span>Curiosity</span></div></div></div><div className="portrait reveal" aria-label="Professional portrait placeholder"><div className="portraitGlow"/><div className="portraitInner"><span>MR</span><small>YOUR PHOTO</small></div><div className="floating">Currently available<br/><b>for selected projects</b></div></div></section>
 <section id="about" className="section wrap"><div className="sectionLabel reveal">01 — About</div><div className="aboutGrid"><div className="reveal"><h2>Thoughtful work,<br/><em>built to last.</em></h2></div><div className="aboutText reveal"><p>I’m a multidisciplinary professional who enjoys the space between code and design. My work focuses on making complex products feel simple, useful and unmistakably human.</p><p>I collaborate with founders, teams and independent brands from early concept through launch — shaping the strategy, interface and implementation.</p><a className="textLink" href="#contact">Tell me about your project →</a></div></div></section>
 <section className="section soft"><div className="wrap"><div className="sectionLabel reveal">02 — Capabilities</div><div className="skillsGrid reveal">{skills.map((s,i)=><div className="skill" key={s}><span>{String(i+1).padStart(2,"0")}</span>{s}</div>)}</div></div></section>
 <section id="work" className="section wrap"><div className="sectionLabel reveal">03 — Selected work</div><div className="workHead reveal"><h2>A few things I’ve<br/><em>made recently.</em></h2><p>Selected case-study placeholders ready to be replaced with real projects, screenshots and live URLs.</p></div><div className="projects">{projects.map((p,i)=><article className="project reveal" key={p.title}><div className={'projectVisual v'+(i%4)}><span>{String(i+1).padStart(2,"0")}</span><b>{p.title}</b></div><div className="projectBody"><p className="projectType">{p.type}</p><h3>{p.title}</h3><p>{p.description}</p><small>{p.stack}</small><a href={p.href}>View project ↗</a></div></article>)}</div></section>
 <section id="experience" className="section soft"><div className="wrap"><div className="sectionLabel reveal">04 — Experience</div><div className="timeline"><div className="timeItem reveal"><div className="year">2023 — Now</div><div><h3>Independent Developer & Designer</h3><p>Partnering with teams and founders to design and build digital products, brand sites and scalable interfaces.</p></div></div><div className="timeItem reveal"><div className="year">2021 — 2023</div><div><h3>Product Designer · Studio North</h3><p>Led interface design, design systems and front-end collaboration across web and SaaS projects.</p></div></div><div className="timeItem reveal"><div className="year">2019 — 2021</div><div><h3>Front-end Developer · Bright Labs</h3><p>Built responsive React experiences and worked closely with design and product teams.</p></div></div></div></div></section>
 <section className="section wrap"><div className="quote reveal"><span>“</span><p>Good digital work should feel obvious in the hands of the person using it — even when a lot of thinking happened behind the scenes.</p><small>— Maya Rao</small></div></section>
 <section id="contact" className="section contact"><div className="wrap contactGrid"><div className="reveal"><div className="sectionLabel">05 — Contact</div><h2>Have an idea?<br/><em>Let’s make it real.</em></h2><p>Tell me a little about what you’re building, what you need help with, and where you want to go next.</p><div className="socials"><a href="mailto:hello@example.com">Email</a><a href="https://linkedin.com" target="_blank">LinkedIn</a><a href="https://github.com" target="_blank">GitHub</a><a href="https://twitter.com" target="_blank">Twitter / X</a></div></div><form className="form reveal" onSubmit={submit}><label>Name<input name="name" required minLength={2} placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Project details<textarea name="message" required minLength={20} placeholder="What are you working on?"></textarea></label><button className="button primary" type="submit">{sent?"Message ready ✓":"Send enquiry →"}</button>{sent&&<p className="formNote" role="status">Demo form submitted. Connect this endpoint to an email service before launch.</p>}</form></div></section>
 <footer><div className="wrap footerInner"><div><a className="logo" href="#top">MR<span>.</span></a><p>Developer, designer & creative technologist.</p></div><div className="footerLinks"><a href="#about">About</a><a href="#work">Work</a><a href="#experience">Experience</a><a href="#contact">Contact</a></div><small>© 2026 Maya Rao. Built with Next.js.</small></div></footer>
 </main>
}